name: tap_invest_app
description: A Flutter application for TAP Invest company details
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  
  # Dependency Injection
  get_it: ^7.7.0
  injectable: ^2.4.4
  
  # HTTP requests
  http: ^1.4.0
  
  # Charts - Using fl_chart instead of charts_flutter
  fl_chart: ^0.68.0
  provider: ^6.0.0
  
  # Haptic Feedback
  haptic_feedback: ^0.5.1+1
  
  # JSON handling
  json_annotation: ^4.9.0
  
  # UI Components
  cupertino_icons: ^1.0.8
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code generation
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  injectable_generator: ^2.6.2
  
  # Linting
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true